"""empty message

Revision ID: 0954aaee43ce
Revises: 15b1392db281
Create Date: 2024-11-23 10:44:52.780868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '0954aaee43ce'
down_revision: Union[str, None] = '15b1392db281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('age_groups', 'age_from',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('age_groups', 'age_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('age_groups', 'age_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('age_groups', 'age_from',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
