"""empty message

Revision ID: 51943a16bcf4
Revises: a486c3dcb91b
Create Date: 2024-11-23 18:02:45.768041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '51943a16bcf4'
down_revision: Union[str, None] = 'a486c3dcb91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m2m_ages')
    op.drop_table('ages')
    op.drop_constraint('unique_sport_and_columns', 'event_types', type_='unique')
    op.create_unique_constraint(None, 'event_types', ['sport'])
    op.drop_column('event_types', 'category')
    op.add_column('events', sa.Column('category', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'category')
    op.add_column('event_types', sa.Column('category', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_types', type_='unique')
    op.create_unique_constraint('unique_sport_and_columns', 'event_types', ['sport', 'category'])
    op.create_table('ages',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('m2m_ages',
    sa.Column('age_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['age_id'], ['ages.id'], name='m2m_ages_age_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='m2m_ages_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='m2m_ages_pkey')
    )
    # ### end Alembic commands ###
