"""empty message

Revision ID: 54b2061f83a0
Revises: 
Create Date: 2024-11-23 09:01:12.334508

"""
from typing import Sequence, Union, List

from alembic import op
import sqlalchemy as sa
from polyfactory import AsyncPersistenceProtocol

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory,T

from storage.db.models import SportEvent, Location






# revision identifiers, used by Alembic.
revision: str = '54b2061f83a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
                    sa.Column('sport', sa.String(length=250), nullable=False),
                    sa.Column('category', sa.String(length=250), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('category'),
                    sa.UniqueConstraint('sport')
                    )
    op.create_table('files',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('file_path', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('locations',
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('region', sa.String(), nullable=True),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('roles',
                    sa.Column('name', sa.String(length=90), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.Column('login', sa.String(length=200), nullable=False),
                    sa.Column('password', sa.String(length=1024), nullable=False),
                    sa.Column('first_name', sa.String(length=320), nullable=False),
                    sa.Column('middle_name', sa.String(length=320), nullable=False),
                    sa.Column('last_name', sa.String(length=320), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login'),
                    sa.UniqueConstraint('phone')
                    )
    op.create_table('events',
                    sa.Column('name', sa.String(length=700), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=False),
                    sa.Column('participants_count', sa.Integer(), nullable=False),
                    sa.Column('type_event_id', sa.Integer(), nullable=False),
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['type_event_id'], ['event_types.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('pdf_files',
                    sa.Column('file_id', sa.Integer(), nullable=False),
                    sa.Column('touch_date', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sessions',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_files',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('file_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_roles',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('age_groups',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('age_from', sa.Integer(), nullable=False),
                    sa.Column('age_to', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('competitions',
                    sa.Column('type', sa.String(length=80), nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)

    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitions')
    op.drop_table('age_groups')
    op.drop_table('user_roles')
    op.drop_table('user_files')
    op.drop_table('sessions')
    op.drop_table('pdf_files')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('locations')
    op.drop_table('files')
    op.drop_table('event_types')
    # ### end Alembic commands ###
