"""empty message

Revision ID: a486c3dcb91b
Revises: a384b23a22b2
Create Date: 2024-11-23 17:16:04.823746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = 'a486c3dcb91b'
down_revision: Union[str, None] = 'a384b23a22b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_types_category_key', 'event_types', type_='unique')
    op.drop_constraint('event_types_sport_key', 'event_types', type_='unique')
    op.create_unique_constraint('unique_sport_and_columns', 'event_types', ['sport', 'category'])
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_sport_and_columns', 'event_types', type_='unique')
    op.create_unique_constraint('event_types_sport_key', 'event_types', ['sport'])
    op.create_unique_constraint('event_types_category_key', 'event_types', ['category'])
    # ### end Alembic commands ###
